#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
ODIN_UI_ROOT=$(realpath $HERE/..)
SELENIUM_VERSION=latest
CONTAINER_NAME=odin-ui-selenium

if [ "$#" -eq 0 ]; then
    IMAGE=selenium/standalone-firefox:$SELENIUM_VERSION
    DEBUG=false
elif [ "'$*'" == "'--debug'" ]; then
    IMAGE=selenium/standalone-firefox-debug:$SELENIUM_VERSION
    DEBUG=true
else
    echo "Usage: $0 [--debug]"
    exit 1
fi

echo "Starting docker container"
docker run -d --rm \
       --name $CONTAINER_NAME \
       --network=host \
       -v ${ODIN_UI_ROOT}:/host \
       selenium/standalone-firefox-debug:$SELENIUM_VERSION

if [ "$DEBUG" == "true" ]; then
    echo "Connect a VNC client to localhost:5900 to see the browser"
fi

echo "Run ./scripts/selenium-stop to stop the server"
